### PR TITLE
Add geojson template

### PR DESCRIPTION
**Pull request by patrickniepel**
• Added the template to generate the geojson api

### CODE REVIEW

**Comment by EmDee** [comment]
@patrickniepel Commit message has `WIP`.
@telip007 Can you review here since you're the master of API generation?

**Comment by telip007** [comment]
Is this done or still wip?

**Review by telip007 — APPROVED** [review]

**Comment by patrickniepel** [comment]
@telip007 It's done. Just forgot to "unwip" it

**Comment by telip007** [comment]
Ok @patrickniepel all in all it's a correct template file, but I will keep this PR open until the MR in the SDK is done with generation.

**Pull request merged**
